server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true


spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://221.168.38.224/user?serverTimezone=Asia/Seoul
#    username: root
#    password: root

    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/reit
    username: garfield
    password: jaeuk@2647

  devtools:
    livereload:
      port: 35730

  jpa:
    open-in-view: true  #default true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

    show-sql: true
    properties:
      hibernate.format_sql: true
#      hibernate.id.new_generator_mappings: false


  jackson:
    serialization:
      fail-on-empty-beans: false


      
      
      
      
      